services:
  - type: web
    name: prestamo-inso-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: SPRING_PROFILES_ACTIVE=production java -Dserver.port=$PORT -jar target/prestamo-inso-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: AWS_RDS_PASSWORD
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: MYSQL_URL
        value: jdbc:mysql://database-1.cdo668soo2u9.us-east-2.rds.amazonaws.com:3306/prestamo_inso_db?useSSL=true&requireSSL=true&serverTimezone=UTC&characterEncoding=utf8
        sync: false
      - key: MYSQL_USERNAME
        sync: false
      - key: MYSQL_PASSWORD
        sync: false